server:
  port: 8080

spring:
  application:
    name: beatbox

  datasource:
    url: jdbc:h2:mem:beatboxdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: update     # use validate in prod
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

# JWT configuration
auth:
  secret: I8SGWYczIrnqFIjHmzHOkU0Hb+8KC2X6uBHAit1h0z4=
  expirationMinutes: 60


spring-doc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
